Update realmAuctionRequest.yml

diff --git a/.github/workflows/realmAuctionRequest.yml b/.github/workflows/realmAuctionRequest.yml
--- a/.github/workflows/realmAuctionRequest.yml
+++ b/.github/workflows/realmAuctionRequest.yml
@@ -26,4 +26,33 @@ jobs:
         env:
           BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
           BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
-        run: python gather_data.py
+        run: python auctionDataRequest.py
+      - name: Commit and push changes
+        run: |
+          set -e  # Exit script on any command failure
+      
+          git config --global user.name "github-actions"
+          git config --global user.email "github-actions@github.com"
+          git config pull.rebase true  # Rebase
+      
+          git add data/
+          
+          # Commit only if there are changes
+          if git diff --cached --quiet; then
+            echo "No changes to commit"
+          else
+            git commit -m "Updated Leaderboard data"
+          fi
+      
+          # Pull latest changes, fail only on actual errors
+          if ! git pull --rebase; then
+            echo "Error during git pull" >&2
+            exit 1
+          fi
+      
+          # Push changes, fail if there's an actual error
+          if ! git push; then
+            echo "Error during git push" >&2
+            exit 1
+          fi
+
